'use client';
import {useEffect,useState} from 'react';
import {api} from '../../lib/api';
// @ts-ignore JavaScript module shared with the standalone offline verifier.
import {verifyPackage} from '../../lib/proof-verifier';
export default function Verify(){const[job,setJob]=useState('J-2231'),[key,setKey]=useState(''),[pkg,setPkg]=useState<any>(null),[result,setResult]=useState<any>(null),[message,setMessage]=useState('');
 useEffect(()=>{const linked=new URLSearchParams(window.location.search).get('job');if(linked)setJob(linked);setKey(localStorage.getItem('hep-pinned-key')||'')},[]);
 const check=async(p:any)=>{setPkg(p);try{const pinned=key||localStorage.getItem('hep-pinned-key')||'';setResult(await verifyPackage(p,pinned,JSON.parse(localStorage.getItem('hep-anchors')||'[]')))}catch(e:any){setMessage(e.message)}};
 const download=(value:any,name:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click()};
 return <main className="workspace"><p className="eyebrow">CUSTOMER-HELD HISTORY</p><h1>Trust you can check.</h1><p className="muted">Verify the provider signature, event chain, SLA calculation, and the history you retained. File verification performs no network requests.</p>
 <section className="panel"><h2>1. Pin your onboarding key</h2><p>Compare the fingerprint against your service contract before pinning. A key from a package alone does not establish trust.</p><textarea placeholder="Base64 public key from onboarding" value={key} onChange={e=>setKey(e.target.value)} /><div className="toolbar"><button onClick={()=>{localStorage.setItem('hep-pinned-key',key.trim());setMessage('Onboarding key pinned.')}}>Pin key</button><button onClick={async()=>{try{const x=await api<any>('/.well-known/rivet-keys.json');setKey(x.keys[0].public_key);setMessage('Published fingerprint: '+x.keys[0].fingerprint+'. Compare with your contract before pinning.')}catch(e:any){setMessage(e.message)}}}>Show published key</button></div></section>
 <section className="panel"><h2>2. Open a signed record</h2><div className="toolbar"><input value={job} onChange={e=>setJob(e.target.value)} /><button onClick={async()=>{try{await check(await api(`/jobs/${job}/package`))}catch(e:any){setMessage(e.message)}}}>Load service package</button><input type="file" accept=".json" onChange={async e=>{if(e.target.files?.[0])try{await check(JSON.parse(await e.target.files[0].text()))}catch(x:any){setMessage(x.message)}}} /></div></section>
 {result&&<section className="panel"><span className={`badge ${result.valid?'success':'danger'}`}>{result.valid?'SERVICE RECORD VERIFIED':'VERIFICATION FAILED'}</span><h2>{pkg.body.machine_id} · {pkg.body.job_id}</h2>{result.valid?<p>{result.anchored?'Matches the history you previously retained.':'Signature and internal chain valid. No previous customer-held head for this machine.'}</p>:result.errors.map((x:string)=><p key={x} className="error">{x}</p>)}{result.sla&&<p>SLA recomputed: {result.sla.met?'met':'missed'} · margin {result.sla.margin_minutes} minutes</p>}<p>Acceptance: {pkg.body.acceptance}</p><p>Reconciliation: {pkg.body.reconciliation?.outcome}</p><code>{result.head}</code><div className="toolbar"><button disabled={!result.valid} onClick={()=>{const a=JSON.parse(localStorage.getItem('hep-anchors')||'[]');a.push({machine_id:pkg.body.machine_id,machine_seq:pkg.body.events.length,machine_hash:pkg.body.head});localStorage.setItem('hep-anchors',JSON.stringify(a));setMessage('Verified head retained on this customer device.')}}>Remember verified head</button><button onClick={()=>download(pkg,`${job}-service-package.json`)}>Download package</button></div></section>}
 <section className="panel"><h2>3. Keep your own history</h2><button onClick={()=>download(JSON.parse(localStorage.getItem('hep-anchors')||'[]'),'customer-held-history.json')}>Export remembered heads</button><input type="file" accept=".json" onChange={async e=>{if(e.target.files?.[0]){try{const a=JSON.parse(await e.target.files[0].text());if(!Array.isArray(a))throw Error('History must be an array');localStorage.setItem('hep-anchors',JSON.stringify(a));setMessage('Customer-held history imported.')}catch(x:any){setMessage(x.message)}}}} /><p className="muted">A fully rewritten and re-signed history can pass internal checks. A customer-held earlier head reveals the divergence.</p></section>{message&&<p role="status" className="notice">{message}</p>}</main>;
}
