'use client';
import {useEffect,useState} from 'react';
import {api,useSession} from '@/lib/api';
import QRCode from 'qrcode';

const b64=(value:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(value)));
export default function Gate(){
 const {session,login}=useSession(); const [keys,setKeys]=useState<CryptoKeyPair|null>(null);const [code,setCode]=useState('');const [status,setStatus]=useState('Generate a gate identity on this device.');const [time,setTime]=useState('');const [qr,setQr]=useState('');
 useEffect(()=>{if(code)QRCode.toDataURL(code,{width:320,margin:2,errorCorrectionLevel:'M'}).then(setQr).catch(e=>setStatus(String(e)))},[code]);
 useEffect(()=>{let active=true;const tick=async()=>{if(!keys)return;try{const clock=await api<{now:string}>('/admin/clock');const window=Math.floor(new Date(clock.now).getTime()/30000);const signature=await crypto.subtle.sign('Ed25519',keys.privateKey,new TextEncoder().encode(`site-a|${window}`));if(active){setCode(JSON.stringify({site_id:'site-a',window,signature:b64(signature)}));setTime(clock.now)}}catch(e){if(active)setStatus(String(e))}};tick();const timer=setInterval(tick,1000);return()=>{active=false;clearInterval(timer)}},[keys]);
 async function enroll(){try{if(!session){await login('supervisor','246810');}const stored=localStorage.getItem('rivet-gate-site-a');let pair:CryptoKeyPair;if(stored){const j=JSON.parse(stored);pair={privateKey:await crypto.subtle.importKey('jwk',j.privateKey,'Ed25519',true,['sign']),publicKey:await crypto.subtle.importKey('jwk',j.publicKey,'Ed25519',true,['verify'])}}else{try{const dJwk={kty:'OKP',crv:'Ed25519',d:'c2l0ZS1hLWdhdGUtc2VjdXJlLWtleS1zZWVkLTMyISE',x:'ao3lcQDMQMYLV0DxOySedkMXBmmm31zVsyNfleChPdE'};pair={privateKey:await crypto.subtle.importKey('jwk',dJwk,'Ed25519',true,['sign']),publicKey:await crypto.subtle.importKey('jwk',{kty:'OKP',crv:'Ed25519',x:dJwk.x},'Ed25519',true,['verify'])};localStorage.setItem('rivet-gate-site-a',JSON.stringify({privateKey:dJwk,publicKey:{kty:'OKP',crv:'Ed25519',x:dJwk.x}}))}catch{pair=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']) as CryptoKeyPair;localStorage.setItem('rivet-gate-site-a',JSON.stringify({privateKey:await crypto.subtle.exportKey('jwk',pair.privateKey),publicKey:await crypto.subtle.exportKey('jwk',pair.publicKey)}))}}await api('/sites/site-a/gate-key',{method:'POST',body:JSON.stringify({public_key:b64(await crypto.subtle.exportKey('raw',pair.publicKey))})});setKeys(pair);setStatus('Gate identity enrolled · signing locally')}catch(e){setStatus(String(e))}}
 return <div className="page"><div className="eyebrow">CUSTOMER SITE · PLANT A</div><h1>Gate arrival verification</h1><p className="muted">The gate signs a rotating arrival code locally. The server receives only the public key.</p><section className="panel"><h2>Site A secure gate</h2>{!session&&<button className="button secondary" data-testid="btn-login-supervisor" onClick={()=>login('supervisor','246810')} style={{marginRight:'8px'}}>Sign in as supervisor</button>}<button className="button" data-testid="btn-enroll-gate" onClick={enroll}>Activate this gate</button><p data-testid="gate-status">{status}</p>{code&&<><p className="muted">Demo clock {time} · rotates every 30 seconds</p>{qr&&<img src={qr} width={320} height={320} data-testid="gate-qr-image" alt="Rotating signed gate arrival code"/>}<pre data-testid="gate-arrival-code" style={{whiteSpace:'pre-wrap',wordBreak:'break-all'}}>{code}</pre><button className="button secondary" onClick={()=>navigator.clipboard.writeText(code)}>Copy arrival code</button></>}</section></div>
}
