'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,useSession} from '../../lib/api';
export default function Portal(){
 const {session}=useSession();const[jobs,setJobs]=useState<any[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<any>(null),[pin,setPin]=useState(''),[message,setMessage]=useState(''),[line,setLine]=useState('labour'),[presence,setPresence]=useState(false);
 const refresh=async()=>{const data=await api<any>('/jobs');const list=Array.isArray(data)?data:data.items||data.jobs||[];setJobs(list);if(!selected&&list.length)setSelected(list[0].id)};
 useEffect(()=>{if(session)refresh().catch(e=>setMessage(e.message))},[session]);
 useEffect(()=>{if(selected&&session)api<any>(`/jobs/${selected}`).then(setDetail).catch(e=>setMessage(e.message))},[selected,session]);
 const act=async(path:string,body:any={})=>{try{const result=await api<any>(path,{method:'POST',body:JSON.stringify(body)});setMessage('Recorded in the audit history.');await refresh();setDetail(await api<any>(`/jobs/${selected}`));return result}catch(e:any){setMessage(e.message)}};
 const j=detail?.job||detail;
 return <main className="workspace"><div className="page-heading"><div><p className="eyebrow">CUSTOMER WORKSPACE</p><h1>Your service, on record.</h1><p className="muted">Track commitments, confirm access, and review the evidence behind completion.</p></div><Link className="button" href="/verify">Verify a record ↗</Link></div>
 <div className="panel"><h2>Service requests</h2><div className="toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}>{jobs.map(x=><option key={x.id} value={x.id}>{x.id} · {x.machine_id} · {x.state}</option>)}</select><button onClick={()=>act('/requests',{machine_id:'M-104',fault:'hydraulic_leak',description:'Urgent hydraulic leak'})}>Request M-104 service</button></div></div>
 {j&&<><div className="stats-grid"><div className="stat-card"><small>Equipment</small><h2>{j.machine_id}</h2><span>{j.site_id}</span></div><div className="stat-card"><small>Service stage</small><h2>{j.state?.replaceAll('_',' ')}</h2></div><div className="stat-card"><small>Customer acceptance</small><h2>{j.acceptance}</h2><span>{j.reconciliation?.outcome||'Awaiting report'}</span></div></div>
 <section className="panel"><h2>Site commitments</h2><p className="muted">Customer-confirmed access and permit obligations support an accurate service timeline.</p>{j.commitments?.filter((c:any)=>['ACCESS_WINDOW','SHUTDOWN_WINDOW','PERMIT_TO_WORK'].includes(c.type)).map((c:any)=><div className="toolbar" key={c.id}><span>{c.type.replaceAll('_',' ')} · {c.state}</span><button onClick={()=>act(`/customer-commitments/${c.id}/confirm`)}>Confirm</button><button onClick={()=>act(`/customer-commitments/${c.id}/fulfil`)}>Fulfilled</button></div>)}<button onClick={()=>act(`/pauses/pause:${selected}/confirm`)}>Confirm recorded permit pause</button><button onClick={()=>act(`/jobs/${selected}/machine-running`)}>Confirm machine running</button></section>
 <section className="panel"><h2>Completion evidence</h2><p>Report fingerprint: <code>{j.report_hash||'No submitted report'}</code></p>{j.report&&<><table><thead><tr><th>Part</th><th>Reported</th><th>Store issued</th></tr></thead><tbody>{Object.entries(j.report.parts||{}).map(([k,v])=><tr key={k}><td>{k}</td><td>{String(v)}</td><td>{j.issued_parts?.[k]||0}</td></tr>)}</tbody></table><p>{j.report.notes}</p><p>Checklist: {j.report.checklist?.join(' · ')}</p></>}
 <label><input type="checkbox" checked={presence} onChange={e=>setPresence(e.target.checked)}/> I confirm the technician was present at this site.</label><div className="toolbar"><input type="password" inputMode="numeric" placeholder="Supervisor PIN" value={pin} onChange={e=>setPin(e.target.value)} /><button disabled={!j.report_hash} onClick={()=>act(`/jobs/${selected}/accept`,{pin,device_id:session?.device_id,report_hash:j.report_hash,confirm_presence:presence})}>Accept this exact report</button><Link className="button secondary" href={`/verify?job=${selected}`}>Check signed history</Link></div><p className="muted">Acceptance requires the registered supervisor device. Missing fix confirmation remains visible.</p></section>
 <section className="panel"><h2>Raise a named-line dispute</h2><div className="toolbar"><select value={line} onChange={e=>setLine(e.target.value)}>{['labour','sla','presence','fix',...Object.keys(j.report?.parts||{})].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>act(`/jobs/${selected}/dispute`,{lines:[line],reason:'Customer requests review'})}>Dispute selected line</button></div><p className="muted">Only the named lines are held. Other invoice lines remain payable.</p></section></>}{message&&<p className="notice" role="status">{message}</p>}
 </main>;
}
